-- WQMS Supabase schema
-- Run this in Supabase Dashboard → SQL Editor

-- Enable UUID extension (optional, for id columns)
-- We use bigint serial IDs to match existing API.

-- 1. Water quality readings (from sensors / MQTT)
CREATE TABLE IF NOT EXISTS water_quality_readings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  node_id text,
  location text,
  temperature real,
  turbidity real,
  ph real,
  nh3 real,
  dissolved_oxygen real,
  flow_rate real,
  wqi integer,
  timestamp timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_readings_node_id ON water_quality_readings (node_id);
CREATE INDEX IF NOT EXISTS idx_readings_timestamp ON water_quality_readings (timestamp DESC);
-- Index on date(timestamp) omitted: Postgres requires IMMUTABLE functions in index expressions.

-- 2. Alerts
CREATE TABLE IF NOT EXISTS alerts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  node_id text,
  title text,
  detail text,
  severity text,
  type text,
  node_name text,
  parameter text,
  value real,
  threshold_min real,
  threshold_max real,
  status text DEFAULT 'active',
  timestamp timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_alerts_timestamp ON alerts (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_severity ON alerts (severity);
CREATE INDEX IF NOT EXISTS idx_alerts_status_timestamp ON alerts (status, timestamp DESC);

-- 3. Daily summaries (aggregates for reports)
CREATE TABLE IF NOT EXISTS daily_summaries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date date NOT NULL,
  node_id text NOT NULL,
  location text,
  avg_temperature real,
  avg_turbidity real,
  avg_ph real,
  avg_nh3 real,
  avg_dissolved_oxygen real,
  avg_flow_rate real,
  avg_wqi real,
  min_wqi integer,
  max_wqi integer,
  reading_count integer,
  created_at timestamptz DEFAULT now(),
  UNIQUE(date, node_id)
);

CREATE INDEX IF NOT EXISTS idx_summaries_date ON daily_summaries (date DESC);
CREATE INDEX IF NOT EXISTS idx_summaries_node_id ON daily_summaries (node_id);

-- 4. Nodes (replaces localStorage; sync across devices when using Supabase)
CREATE TABLE IF NOT EXISTS nodes (
  id text PRIMARY KEY,
  name text,
  location text,
  status text DEFAULT 'offline',
  lat double precision,
  lng double precision,
  last_maintenance timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Seed default nodes (optional; run once)
INSERT INTO nodes (id, name, location, status, lat, lng)
VALUES
  ('N-001', 'River A - Bridge', 'Villanueva', 'online', 8.5892, 124.7819),
  ('N-002', 'River A - Intake', 'Tagoloan', 'testing', 8.5411, 124.7522),
  ('N-003', 'Creek B - Outflow', 'Cagayan de Oro', 'offline', 8.4822, 124.6472)
ON CONFLICT (id) DO NOTHING;

-- Row Level Security (RLS): enable then allow anon read/write for WQMS (no auth).
-- For production with auth, restrict by user/role.
ALTER TABLE water_quality_readings ENABLE ROW LEVEL SECURITY;
ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_summaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE nodes ENABLE ROW LEVEL SECURITY;

-- Policies: allow all for anon key (dashboard + serverless/backend use same DB)
CREATE POLICY "Allow all on water_quality_readings" ON water_quality_readings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on alerts" ON alerts FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on daily_summaries" ON daily_summaries FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on nodes" ON nodes FOR ALL USING (true) WITH CHECK (true);

-- Optional: updated_at trigger for nodes
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS nodes_updated_at ON nodes;
CREATE TRIGGER nodes_updated_at
  BEFORE UPDATE ON nodes
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
