-- Example Supabase schema for the MQTT bridge (sensor_readings)
-- Run in Supabase Dashboard → SQL Editor
-- Use this if the bridge writes to sensor_readings; otherwise point SUPABASE_TABLE at water_quality_readings.

CREATE TABLE IF NOT EXISTS sensor_readings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  node_id text NOT NULL,
  location text,
  temperature real,
  turbidity real,
  ph real,
  nh3 real,
  dissolved_oxygen real,
  flow_rate real,
  wqi integer,
  timestamp timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sensor_readings_node_id ON sensor_readings (node_id);
CREATE INDEX IF NOT EXISTS idx_sensor_readings_timestamp ON sensor_readings (timestamp DESC);

-- RLS (optional): enable and allow service role / anon as needed
ALTER TABLE sensor_readings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow service role full access on sensor_readings"
  ON sensor_readings FOR ALL
  USING (true)
  WITH CHECK (true);

-- Allow anon (dashboard) to read for Reports page
CREATE POLICY "Allow anon read on sensor_readings"
  ON sensor_readings FOR SELECT
  USING (true);
