-- Test Evaluation Mode support
-- test_runs: one row per evaluation session started from the dashboard
CREATE TABLE IF NOT EXISTS test_runs (
  id          text        PRIMARY KEY,          -- UUID generated by backend
  started_at  bigint      NOT NULL,             -- epoch ms
  ends_at     bigint      NOT NULL,             -- started_at + duration_ms
  duration_ms bigint      NOT NULL,
  interval_ms bigint      NOT NULL,             -- transmission frequency
  node_id     text,                             -- null = all nodes
  status      text        NOT NULL DEFAULT 'running', -- running | completed | stopped
  stopped_at  bigint,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- Link individual telemetry packets to the test run they belong to
ALTER TABLE sensor_readings
  ADD COLUMN IF NOT EXISTS test_run_id text REFERENCES test_runs(id);

CREATE INDEX IF NOT EXISTS idx_sensor_readings_test_run_id
  ON sensor_readings (test_run_id)
  WHERE test_run_id IS NOT NULL;
